import { Inter } from "next/font/google";
import "./globals.css";
import { CookiesProvider } from 'next-client-cookies/server';
import { PostProvider } from './context/PostContext';


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "FindYourPet",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <PostProvider>
          <CookiesProvider>
            {children}
          </CookiesProvider>
        </PostProvider>
      </body>
    </html>
  );
}
